/*
 * Generated by Rarma - Ruby to SQF Compiler
 * Source: demo.rb
 */

class TestMission {
    def __init__() {
        this.name = "Demo Mission";
        this.players = [];
    };

    def add_player(player_name) {
        this.players pushBack player_name;
        diag_log format["Added player: %1", player_name];
    };

    def start() {
        diag_log format["Starting mission: %1", this.name];
        diag_log format["Total players: %1", count this.players];
    };
};

/*
 * Main execution
 */
_mission = ["new"] call TestMission;
["add_player", "Alice"] call _mission;
["add_player", "Bob"] call _mission;
["start"] call _mission;