/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("TestMission")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("name","Demo Mission");
    MEMBER("players",[]);
};

PUBLIC FUNCTION("any","add_player") {
this.players pushBack player_name
    ;
diag_log "Added player: " + str(player_name);
    ;
};

PUBLIC FUNCTION("any","start") {
diag_log "Starting mission: " + str(MEMBER("name",nil));
    ;
diag_log "Total players: " + str(count MEMBER("players",nil));
    ;
};

ENDCLASS;

mission = ["new"] call TestMission;
MEMBER("add_player",["Alice"])
;
MEMBER("add_player",["Bob"])
;
MEMBER("start",nil)
;