/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

// Imported math as math
// Imported random as rnd
// Imported math.sqrt as sqrt
// Imported math.sin as sin
// Imported random.choice as choice
PUBLIC FUNCTION("any","test_imports") {
    x = sqrt 16;
    y = sin (0 * 180 / 3.14159265359);
    z = 0 + (random (1 - 0));
    item = ["a", "b", "c"] select (floor random count ["a", "b", "c"]);
    unknown
};

diag_log test_imports();
;