/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

// Imported random as random
// Imported math as math
PUBLIC FUNCTION("any","create_units") {
    units = [];
    for "_i" from 0 to (5 - 1) do {
        x = 100 + (random (900 - 100));
        y = 100 + (random (900 - 100));
        unit_name = ("unit_" + str(i));
diag_log (((((("Created unit " + unit_name) + " at (") + str(int(x))) + ", ") + str(int(y))) + ")");
        ;
        unit_info = [["name", unit_name], ["position", [x, y, 0]], ["type", "B_soldier_F"]];
units pushBack unit_info;
        ;
    };
    units
};

PUBLIC FUNCTION("any","move_units_randomly") {
    { // for loop
        current_x = unknown;
        current_y = unknown;
        new_x = (current_x + unknown + (random (50 - unknown)));
        new_y = (current_y + unknown + (random (50 - unknown)));
        new_x = max(0, min(1000, new_x));
        new_y = max(0, min(1000, new_y));
diag_log (((((unknown + " moving to (") + str(int(new_x))) + ", ") + str(int(new_y))) + ")");
        ;
    } forEach units;
};

PUBLIC FUNCTION("any","calculate_distances") {
    for "_i" from 0 to ((count units) - 1) do {
        for "_j" from 0 to ((count units) - 1) do {
            if (_i != _j) then {
                unit1 = unknown;
                unit2 = unknown;
                dx = (unknown - unknown);
                dy = (unknown - unknown);
                distance = sqrt ((dx * dx) + (dy * dy));
                if (distance < 100) then {
diag_log (((((unknown + " and ") + unknown) + " are ") + str(int(distance))) + " meters apart");
                    ;
                };
            };
        };
    };
};

PUBLIC FUNCTION("any","mission_loop") {
diag_log "Starting ArmA 3 mission...";
    ;
    units = create_units();
diag_log (("Created " + str((count units))) + " units");
    ;
    for "_loop" from 0 to (3 - 1) do {
diag_log (("
--- Game Loop " + str((_loop + 1))) + " ---");
        ;
move_units_randomly(units)
        ;
calculate_distances(units)
        ;
    };
diag_log "
Mission complete!";
    ;
};

if (__name__ == "__main__") then {
mission_loop()
    ;
};