/*
 * Generated by Rarma - Ruby to SQF Compiler
 * Source: test_mission.rb
 */

class MyMission {
    /*
     * Constructor for MyMission
     */
    def __init__() {
        this.players = [];
        this.mission_name = "Test Mission";
    };

    /*
     * Add a player to the mission
     */
    def add_player(name) {
        this.players pushBack name;
    };

    /*
     * Start the mission
     */
    def start_mission() {
        diag_log format["Starting mission: %1", this.mission_name];
        {
            diag_log format["Player: %1", _x];
        } forEach this.players;
    };

    /*
     * Check mission conditions
     */
    def check_condition() {
        if (count this.players > 0) then {
            true
        } else {
            false
        };
    };
};

/*
 * Main execution
 */
_mission = ["new"] call MyMission;
["add_player", "Player1"] call _mission;
["start_mission"] call _mission;

if ([_mission, "check_condition"] call MyMission) then {
    diag_log "Mission ready!";
};