/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("RandomUnitsMission")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("unit_types",["B_Soldier_F", "O_Soldier_F", "I_Soldier_F", "B_Soldier_GL_F", "O_Soldier_AR_F", "I_Soldier_M_F"]);
    MEMBER("created_units",[]);
};

PUBLIC FUNCTION("any","get_random_position") {
    x = 0 + (random (30720 - 0));
    y = 0 + (random (30720 - 0));
    [x, y, 0]
};

PUBLIC FUNCTION("any","create_random_unit") {
    unit_type = MEMBER("unit_types",nil) select (floor random count MEMBER("unit_types",nil));
    position = MEMBER("get_random_position",nil);
    unit = [["type", unit_type], ["position", position], ["side", side]];
this.created_units pushBack unit
    ;
    unit
};

PUBLIC FUNCTION("any","create_multiple_units") {
    units = [];
    for "_i" from 0 to (count - 1) do {
        unit = MEMBER("create_random_unit",[side]);
units pushBack unit
        ;
    };
    units
};

PUBLIC FUNCTION("any","get_all_positions") {
    positions = [];
    { // for loop
positions pushBack unknown
        ;
    } forEach MEMBER("created_units",nil);
    positions
};

PUBLIC FUNCTION("any","count_units") {
    count MEMBER("created_units",nil)
};

PUBLIC FUNCTION("any","cleanup_units") {
MEMBER("created_units",[])
    ;
};

ENDCLASS;

mission = ["new"] call RandomUnitsMission;
blufor_units = MEMBER("create_multiple_units",[15, "BLUFOR"]);
opfor_units = MEMBER("create_multiple_units",[10, "OPFOR"]);
independent_units = MEMBER("create_multiple_units",[5, "INDEPENDENT"]);
total_units = MEMBER("count_units",nil);
diag_log "Created " + str(total_units) + " units across the map";
;
all_positions = MEMBER("get_all_positions",nil);
diag_log "Units deployed at " + str(count all_positions) + " locations";
;