/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

// Warning: Import of 'json' not supported in SQF
// Imported typing.List as List (type hints ignored)
PUBLIC FUNCTION("any","test_try_except") {
    _exception_139741637903696 = nil; // Exception tracking
    // Try block
    result = (10 / 2);
    result
    // Except block for ZeroDivisionError
    if (!isNil "_exception_139741637903696") then {
        e = _exception_139741637903696;
        "error"
        _exception_139741637903696 = nil;
    };
    // Except block for Exception
    if (!isNil "_exception_139741637903696") then {
        e = _exception_139741637903696;
        "unknown error"
        _exception_139741637903696 = nil;
    };
    // Finally block
diag_log "cleanup";
    ;
};

PUBLIC FUNCTION("any","test_lambda") {
    square = {x { (x * x) } };
    numbers = [1, 2, 3, 4, 5];
    squares = list(map(square, numbers));
    squares
};

PUBLIC FUNCTION("any","test_list_comprehension") {
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    evens = (numbers select {((x % 2) == 0)} apply {x});
    doubled = (evens apply {(x * 2)});
    doubled
};

PUBLIC FUNCTION("any","test_with_statement") {
    // With statement (context manager)
    ctx = "some_context"; // Context manager
    result = "processing " + str(ctx);
    result
    // End with statement
};

PUBLIC FUNCTION("any","test_json_operations") {
    data = [["name", "test"], ["value", 42], ["items", [1, 2, 3]]];
    json_str = str data;
    _exception_139741637921808 = nil; // Exception tracking
    // Try block
    parsed = parseSimpleArray json_str;
    parsed
    // Except block for any
    if (!isNil "_exception_139741637921808") then {
        [["error", "json parsing not available in SQF"]]
        _exception_139741637921808 = nil;
    };
};

PUBLIC FUNCTION("any","test_break_continue") {
    result = [];
    for "_i" from 0 to (10 - 1) do {
        if (_i == 3) then {
            // Continue statement - not directly supported in SQF
            // Consider restructuring the loop logic
        };
        if (_i == 7) then {
            // Break statement - not directly supported in SQF
            // Consider restructuring the loop logic
        };
result pushBack _i;
        ;
    };
    result
};

PUBLIC FUNCTION("any","main") {
diag_log "Testing improved Parma features...";
    ;
    try_result = test_try_except();
    lambda_result = test_lambda();
    comp_result = test_list_comprehension();
    with_result = test_with_statement();
    json_result = test_json_operations();
    loop_result = test_break_continue();
    [["try_except", try_result], ["lambda", lambda_result], ["comprehension", comp_result], ["with_statement", with_result], ["json", json_result], ["loops", loop_result]]
};

if (__name__ == "__main__") then {
    results = main();
diag_log "Test results:";
    ;
};