"""Core SQF transpiler for Python AST."""
import ast
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


class SQFTranspiler(ast.NodeVisitor):
    """Transpiles Python AST to SQF code."""

    def __init__(self):
        self.output: List[str] = []
        self.indent_level = 0
        self.variables: Dict[str, str] = {}
        self.classes: Dict[str, Dict] = {}
        self.current_class: Optional[str] = None

    def transpile(self, source_code: str) -> str:
        """Transpile Python AST to SQF."""
        try:
            tree = ast.parse(source_code)
            self.visit(tree)
            return self._format_output()
        except SyntaxError as e:
            raise ValueError(f"Invalid Python syntax: {e}")

    def _format_output(self) -> str:
        """Format the generated SQF code."""
        # Add header with OOP macros include
        header = [
            "/*",
            " * Generated by Parma - Python to SQF Transpiler",
            " */",
            '#include "macros/oop.h"',
            ""
        ]

        return "\n".join(header + self.output)

    def _indent(self) -> str:
        """Get current indentation."""
        return "    " * self.indent_level

    def _add_line(self, line: str):
        """Add a line to output with proper indentation."""
        self.output.append(f"{self._indent()}{line}")

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        """Handle class definitions using OOP macros."""
        class_name = node.name

        # Use CLASS macro instead of raw class syntax
        if node.bases:
            # Handle inheritance
            base_name = node.bases[0].id if isinstance(node.bases[0], ast.Name) else "unknown"
            self._add_line(f'CLASS_EXTENDS("{class_name}","{base_name}")')
        else:
            self._add_line(f'CLASS("{class_name}")')

        # Store class info
        self.classes[class_name] = {
            'methods': {},
            'bases': [base.id if isinstance(base, ast.Name) else str(base) for base in node.bases],
            'instance_vars': set()
        }

        # Process class body
        self.current_class = class_name
        for item in node.body:
            self.visit(item)
        self.current_class = None

        self._add_line("ENDCLASS;")
        self._add_line("")

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        """Handle function definitions using OOP macros."""
        func_name = node.name
        args = [arg.arg for arg in node.args.args]

        # Special handling for __init__
        if func_name == "__init__":
            func_name = "constructor"
            # Assume public for now
            self._add_line(f'PUBLIC FUNCTION("array","{func_name}") {{')
        else:
            # Assume public for now - could be enhanced to detect private methods
            return_type = "any"  # Could be enhanced to infer types
            self._add_line(f'PUBLIC FUNCTION("{return_type}","{func_name}") {{')

        self.indent_level += 1

        # Process function body
        for stmt in node.body:
            self.visit(stmt)

        self.indent_level -= 1
        self._add_line("};")
        self._add_line("")

    def visit_Return(self, node: ast.Return) -> None:
        """Handle return statements."""
        if node.value:
            value = self._visit_expr(node.value)
            self._add_line(f"{value}")
        else:
            self._add_line("nil")

    def visit_Expr(self, node: ast.Expr) -> None:
        """Handle expression statements."""
        if isinstance(node.value, ast.Call):
            self.visit_Call(node.value)
            self._add_line(";")
        else:
            self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        """Handle function calls."""
        if isinstance(node.func, ast.Name):
            func_name = node.func.id

            # Handle built-in functions
            if func_name == "print":
                self._handle_print(node)
            elif func_name == "len":
                self._handle_len(node)
            elif func_name == "range":
                self._handle_range(node)
            elif func_name == "random":
                self._handle_random(node)
            elif func_name in self.classes:
                # Class instantiation
                args = []
                for arg in node.args:
                    if isinstance(arg, ast.Str):
                        args.append(f'"{arg.s}"')
                    elif isinstance(arg, ast.Num):
                        args.append(str(arg.n))
                    elif isinstance(arg, ast.Name):
                        args.append(arg.id)
                    else:
                        args.append(self._visit_expr(arg))

                if args:
                    args_str = ", " + ", ".join(args)
                else:
                    args_str = ""
                self.output.append(f'["new"{args_str}] call {func_name}')
            else:
                # Regular function call
                args = []
                for arg in node.args:
                    if isinstance(arg, ast.Str):
                        args.append(f'"{arg.s}"')
                    elif isinstance(arg, ast.Num):
                        args.append(str(arg.n))
                    elif isinstance(arg, ast.Name):
                        args.append(arg.id)
                    else:
                        args.append(self._visit_expr(arg))

                args_str = ", ".join(args)
                self.output.append(f"{func_name}({args_str})")
        elif isinstance(node.func, ast.Attribute):
            # Method call like obj.method() or obj.attr.method()
            method = node.func.attr
            obj_name = "unknown"  # Default

            # Get the object being called on
            if isinstance(node.func.value, ast.Name):
                obj_name = node.func.value.id
                if obj_name == "self":
                    obj = "this"
                else:
                    obj = obj_name
            elif isinstance(node.func.value, ast.Attribute):
                # Handle self.attribute.method() or obj.attribute.method()
                inner_obj = node.func.value.value.id if isinstance(node.func.value.value, ast.Name) else "unknown"
                if inner_obj == "self":
                    obj = f"this.{node.func.value.attr}"
                else:
                    obj = f"{inner_obj}.{node.func.value.attr}"
            else:
                obj = "unknown"

            # Handle specific methods
            if method == "uniform" and obj_name == "random":
                self._handle_random_uniform(node)
            elif method == "choice" and obj_name == "random":
                self._handle_random_choice(node)
            elif method == "append":
                # List append
                args = []
                for arg in node.args:
                    if isinstance(arg, ast.Str):
                        args.append(f'"{arg.s}"')
                    elif isinstance(arg, ast.Num):
                        args.append(str(arg.n))
                    elif isinstance(arg, ast.Name):
                        args.append(arg.id)
                    else:
                        args.append(self._visit_expr(arg))
                args_str = ", ".join(args)
                self.output.append(f"{obj} pushBack {args_str};")
            elif method == "clear":
                if obj == "this.created_units":
                    self.output.append('MEMBER("created_units",[])')
                else:
                    self.output.append(f"{obj} = []")
            else:
                # Generic method call using MEMBER macro
                args = []
                for arg in node.args:
                    if isinstance(arg, ast.Str):
                        args.append(f'"{arg.s}"')
                    elif isinstance(arg, ast.Num):
                        args.append(str(arg.n))
                    elif isinstance(arg, ast.Name):
                        args.append(arg.id)
                    else:
                        args.append("arg")  # Placeholder

                if args:
                    args_str = ", ".join(args)
                    self.output.append(f'MEMBER("{method}",[{args_str}])')
                else:
                    self.output.append(f'MEMBER("{method}",nil)')

    def _handle_print(self, node: ast.Call) -> None:
        """Handle print() calls - convert to diag_log with proper SQF syntax."""
        if node.args:
            arg = node.args[0]
            if isinstance(arg, ast.Str):
                # Simple string
                self.output.append(f'diag_log "{arg.s}";')
            elif isinstance(arg, ast.BinOp) and self._is_string_concatenation(arg):
                # String concatenation - convert to format[]
                parts = self._extract_string_parts(arg)
                if len(parts) == 2:
                    format_str = f'format["%1%2", {parts[0]}, {parts[1]}]'
                    self.output.append(f'diag_log {format_str};')
                else:
                    # Fallback for complex concatenation
                    formatted = self._visit_expr(arg)
                    self.output.append(f'diag_log {formatted};')
            elif isinstance(arg, ast.Name):
                # Variable
                self.output.append(f'diag_log {arg.id};')
            else:
                expr = self._visit_expr(arg)
                self.output.append(f'diag_log {expr};')

    def _is_string_concatenation(self, node: ast.BinOp) -> bool:
        """Check if a binary operation is string concatenation."""
        if isinstance(node.op, ast.Add):
            # Check if both sides are strings or string operations
            left_is_str = isinstance(node.left, ast.Str) or (
                isinstance(node.left, ast.BinOp) and self._is_string_concatenation(node.left)
            )
            right_is_str = isinstance(node.right, ast.Str) or (
                isinstance(node.right, ast.BinOp) and self._is_string_concatenation(node.right)
            )
            return left_is_str and right_is_str
        return False

    def _extract_string_parts(self, node: ast.BinOp) -> list:
        """Extract parts from string concatenation."""
        parts = []
        if isinstance(node.left, ast.Str):
            parts.append(f'"{node.left.s}"')
        elif isinstance(node.left, ast.BinOp):
            parts.extend(self._extract_string_parts(node.left))
        else:
            parts.append(self._visit_expr(node.left))

        if isinstance(node.right, ast.Str):
            parts.append(f'"{node.right.s}"')
        elif isinstance(node.right, ast.BinOp):
            parts.extend(self._extract_string_parts(node.right))
        else:
            parts.append(self._visit_expr(node.right))

        return parts

    def _handle_len(self, node: ast.Call) -> None:
        """Handle len() calls - convert to count with proper SQF syntax."""
        if node.args:
            arg = node.args[0]
            expr = self._visit_expr(arg)
            self.output.append(f"(count {expr})")

    def _handle_range(self, node: ast.Call) -> None:
        """Handle range() calls - convert to SQF for loop."""
        if node.args:
            arg = node.args[0]
            if isinstance(arg, ast.Num) and isinstance(arg.n, (int, float)):
                # For now, just output the range call - needs loop context
                end_val = int(arg.n) - 1
                self.output.append(f"0 to {end_val}")
            elif isinstance(arg, ast.Name):
                self.output.append(f"0 to ({arg.id} - 1)")

    def _handle_random(self, node: ast.Call) -> None:
        """Handle random module calls."""
        # This would be handled by attribute calls, but placeholder
        self.output.append("random")

    def _handle_random_uniform(self, node: ast.Call) -> None:
        """Handle random.uniform() - convert to SQF random."""
        if node.args and len(node.args) >= 2:
            min_val = self._visit_expr(node.args[0])
            max_val = self._visit_expr(node.args[1])
            self.output.append(f"{min_val} + (random ({max_val} - {min_val}))")

    def _handle_random_choice(self, node: ast.Call) -> None:
        """Handle random.choice() - convert to SQF select."""
        if node.args:
            arg = node.args[0]
            arg_str = self._visit_expr(arg)
            self.output.append(f"{arg_str} select (floor random count {arg_str})")

    def visit_Assign(self, node: ast.Assign) -> None:
        """Handle variable assignments."""
        if len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name):
                var_name = target.id
                value = self._visit_expr(node.value)
                if value:  # Only assign if we have a value
                    self._add_line(f"{var_name} = {value};")
                else:
                    self._add_line(f"{var_name} = unknown;")
            elif isinstance(target, ast.Attribute):
                # Handle self.attribute = value using MEMBER macro
                obj_name = target.value.id if isinstance(target.value, ast.Name) else "unknown"
                if obj_name == "self" and self.current_class:
                    attr = target.attr
                    value = self._visit_expr(node.value)
                    if value:
                        self._add_line(f'MEMBER("{attr}",{value});')
                    else:
                        self._add_line(f'MEMBER("{attr}",unknown);')
                    # Track instance variable
                    self.classes[self.current_class]['instance_vars'].add(attr)

    def visit_List(self, node: ast.List) -> str:
        """Handle list literals."""
        elements = []
        for elt in node.elts:
            if isinstance(elt, ast.Str):
                elements.append(f'"{elt.s}"')
            elif isinstance(elt, ast.Num):
                elements.append(str(elt.n))
            else:
                elements.append(self._visit_expr(elt))
        return f"[{', '.join(elements)}]"

    def visit_Dict(self, node: ast.Dict) -> str:
        """Handle dictionary literals - convert to SQF arrays of pairs."""
        if not node.keys:
            return "[]"

        pairs = []
        for key, value in zip(node.keys, node.values):
            if key is None:
                continue  # Skip ** unpacking for now

            if isinstance(key, ast.Str):
                key_str = f'"{key.s}"'
            elif isinstance(key, ast.Num):
                key_str = str(key.n)
            else:
                key_str = self._visit_expr(key)

            value_str = self._visit_expr(value)
            pairs.append(f"[{key_str}, {value_str}]")

        return f"[{', '.join(pairs)}]"

    def visit_If(self, node: ast.If) -> None:
        """Handle if statements."""
        # Convert condition
        condition = self._visit_expr(node.test)

        self._add_line(f"if ({condition}) then {{")
        self.indent_level += 1

        for stmt in node.body:
            self.visit(stmt)

        self.indent_level -= 1
        if node.orelse:
            self._add_line("} else {")
            self.indent_level += 1

            for stmt in node.orelse:
                self.visit(stmt)

            self.indent_level -= 1
        self._add_line("};")

    def visit_For(self, node: ast.For) -> None:
        """Handle for loops."""
        if isinstance(node.iter, ast.Call) and isinstance(node.iter.func, ast.Name) and node.iter.func.id == "range":
            # Handle for i in range(n)
            range_call = node.iter
            if range_call.args:
                range_arg = self._visit_expr(range_call.args[0])
                self._add_line(f"for \"_i\" from 0 to ({range_arg} - 1) do {{")
                self.indent_level += 1

                for stmt in node.body:
                    self.visit(stmt)

                self.indent_level -= 1
                self._add_line("};")
        else:
            # Generic for loop - convert to forEach
            iter_expr = self._visit_expr(node.iter)
            self._add_line("{ // for loop")
            self.indent_level += 1

            for stmt in node.body:
                self.visit(stmt)

            self.indent_level -= 1
            self._add_line(f"}} forEach {iter_expr};")

    def visit_Subscript(self, node: ast.Subscript) -> str:
        """Handle subscript access like dict[key] or list[index] with proper SQF syntax."""
        value = self._visit_expr(node.value)
        if isinstance(node.slice, ast.Index):
            # list[index] or dict[key] - use select command
            index_expr = getattr(node.slice, 'value', None)
            if index_expr:
                index = self._visit_expr(index_expr)
                return f"({value} select {index})"
        elif isinstance(node.slice, ast.Constant):
            # Handle dict['key'] style access
            if isinstance(node.slice.value, str):
                key = node.slice.value
                # For our unit structure, find the value by key
                # Structure: [["type", value], ["position", value], ["side", value]]
                if key == "position":
                    return f"(({value} select 1) select 1)"
                elif key == "type":
                    return f"(({value} select 0) select 1)"
                elif key == "side":
                    return f"(({value} select 2) select 1)"
        return f"({value} select 0)"  # Default fallback with proper parentheses

    def _visit_expr(self, node: ast.AST) -> str:
        """Visit an expression and return its string representation."""
        if isinstance(node, ast.Compare):
            left = self._visit_expr(node.left)
            op = self._cmp_op_to_sqf(node.ops[0])
            right = self._visit_expr(node.comparators[0])
            return f"{left} {op} {right}"
        elif isinstance(node, ast.Name):
            return node.id
        elif isinstance(node, ast.Num):
            return str(node.n)
        elif isinstance(node, ast.Str):
            return f'"{node.s}"'
        elif isinstance(node, ast.Attribute):
            obj_name = node.value.id if isinstance(node.value, ast.Name) else "unknown"
            if obj_name == "self" and self.current_class:
                # Use MEMBER macro for reading self attributes
                return f'MEMBER("{node.attr}",nil)'
            else:
                # For non-self attributes, use direct access
                if obj_name == "self":
                    obj = "this"
                else:
                    obj = obj_name
                return f"{obj}.{node.attr}"
        elif isinstance(node, ast.List):
            return self.visit_List(node)
        elif isinstance(node, ast.Dict):
            return self.visit_Dict(node)
        elif isinstance(node, ast.Call):
            # Handle function calls in expressions
            original_output = self.output
            self.output = []
            self.visit_Call(node)
            result = "".join(self.output).strip()
            self.output = original_output
            return result
        elif isinstance(node, ast.BinOp):
            left = self._visit_expr(node.left)
            op = self._bin_op_to_sqf(node.op)
            right = self._visit_expr(node.right)
            return f"({left} {op} {right})"
        else:
            return "unknown"

    def _bin_op_to_sqf(self, op: ast.operator) -> str:
        """Convert Python binary operators to SQF."""
        if isinstance(op, ast.Add):
            return "+"
        elif isinstance(op, ast.Sub):
            return "-"
        elif isinstance(op, ast.Mult):
            return "*"
        elif isinstance(op, ast.Div):
            return "/"
        elif isinstance(op, ast.Mod):
            return "%"
        else:
            return "+"  # Default

    def _cmp_op_to_sqf(self, op: ast.cmpop) -> str:
        """Convert Python comparison operators to SQF."""
        if isinstance(op, ast.Gt):
            return ">"
        elif isinstance(op, ast.Lt):
            return "<"
        elif isinstance(op, ast.GtE):
            return ">="
        elif isinstance(op, ast.LtE):
            return "<="
        elif isinstance(op, ast.Eq):
            return "=="
        elif isinstance(op, ast.NotEq):
            return "!="
        else:
            return "=="  # Default


def transpile_python_to_sqf(source_code: str) -> str:
    """Main entry point for transpiling Python to SQF."""
    transpiler = SQFTranspiler()
    return transpiler.transpile(source_code)