"""Core SQF transpiler for Python AST."""
import ast
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


class SQFTranspiler(ast.NodeVisitor):
    """Transpiles Python AST to SQF code."""

    def __init__(self):
        self.output: List[str] = []
        self.indent_level = 0
        self.variables: Dict[str, str] = {}
        self.classes: Dict[str, Dict] = {}

    def transpile(self, source_code: str) -> str:
        """Transpile Python source code to SQF."""
        try:
            tree = ast.parse(source_code)
            self.visit(tree)
            return self._format_output()
        except SyntaxError as e:
            raise ValueError(f"Invalid Python syntax: {e}")

    def _format_output(self) -> str:
        """Format the generated SQF code."""
        # Add header comment
        header = [
            "/*",
            " * Generated by Parma - Python to SQF Transpiler",
            " */",
            ""
        ]

        return "\n".join(header + self.output)

    def _indent(self) -> str:
        """Get current indentation."""
        return "    " * self.indent_level

    def _add_line(self, line: str):
        """Add a line to output with proper indentation."""
        self.output.append(f"{self._indent()}{line}")

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        """Handle class definitions."""
        class_name = node.name

        self._add_line(f"class {class_name} {{")
        self.indent_level += 1

        # Store class info
        self.classes[class_name] = {
            'methods': {},
            'bases': [base.id if isinstance(base, ast.Name) else str(base) for base in node.bases]
        }

        # Process class body
        for item in node.body:
            self.visit(item)

        self.indent_level -= 1
        self._add_line("};")
        self._add_line("")

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        """Handle function definitions."""
        func_name = node.name
        args = [arg.arg for arg in node.args.args]

        # Convert to SQF function syntax
        args_str = ", ".join(args) if args else ""
        self._add_line(f"def {func_name}({args_str}) {{")
        self.indent_level += 1

        # Process function body
        for stmt in node.body:
            self.visit(stmt)

        self.indent_level -= 1
        self._add_line("};")
        self._add_line("")

    def visit_Expr(self, node: ast.Expr) -> None:
        """Handle expression statements."""
        if isinstance(node.value, ast.Call):
            self.visit_Call(node.value)
            self._add_line(";")
        else:
            self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        """Handle function calls."""
        if isinstance(node.func, ast.Name):
            func_name = node.func.id

            # Handle built-in functions
            if func_name == "print":
                self._handle_print(node)
            elif func_name == "len":
                self._handle_len(node)
            else:
                # Regular function call
                args = []
                for arg in node.args:
                    if isinstance(arg, ast.Str):
                        args.append(f'"{arg.s}"')
                    elif isinstance(arg, ast.Num):
                        args.append(str(arg.n))
                    elif isinstance(arg, ast.Name):
                        args.append(arg.id)
                    else:
                        args.append(self._visit_expr(arg))

                args_str = ", ".join(args)
                self.output.append(f"{func_name}({args_str})")
        elif isinstance(node.func, ast.Attribute):
            # Method call like obj.method()
            obj = node.func.value.id if isinstance(node.func.value, ast.Name) else "this"
            method = node.func.attr

            args = []
            for arg in node.args:
                if isinstance(arg, ast.Str):
                    args.append(f'"{arg.s}"')
                elif isinstance(arg, ast.Num):
                    args.append(str(arg.n))
                elif isinstance(arg, ast.Name):
                    args.append(arg.id)
                else:
                    args.append("arg")  # Placeholder

            args_str = ", ".join(args)
            self.output.append(f'["{method}", {args_str}] call {obj}')

    def _handle_print(self, node: ast.Call) -> None:
        """Handle print() calls - convert to diag_log."""
        if node.args:
            arg = node.args[0]
            if isinstance(arg, ast.Str):
                self.output.append(f'diag_log "{arg.s}";')
            elif isinstance(arg, ast.Name):
                self.output.append(f'diag_log {arg.id};')
            else:
                self.output.append('diag_log "message";')  # Placeholder

    def _handle_len(self, node: ast.Call) -> None:
        """Handle len() calls - convert to count."""
        if node.args:
            arg = node.args[0]
            if isinstance(arg, ast.Name):
                self.output.append(f'count {arg.id}')

    def visit_Assign(self, node: ast.Assign) -> None:
        """Handle variable assignments."""
        if len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            var_name = node.targets[0].id

            if isinstance(node.value, ast.Str):
                value = f'"{node.value.s}"'
            elif isinstance(node.value, ast.Num):
                value = str(node.value.n)
            elif isinstance(node.value, ast.List):
                value = "[]"  # Placeholder for arrays
            elif isinstance(node.value, ast.Call):
                # Handle constructor calls
                if isinstance(node.value.func, ast.Name) and node.value.func.id in self.classes:
                    value = f'["new"] call {node.value.func.id}'
                else:
                    value = "unknown"  # Placeholder
            else:
                value = "unknown"  # Placeholder

            self._add_line(f"{var_name} = {value};")

    def visit_If(self, node: ast.If) -> None:
        """Handle if statements."""
        # Convert condition
        condition = self._visit_expr(node.test)

        self._add_line(f"if ({condition}) then {{")
        self.indent_level += 1

        for stmt in node.body:
            self.visit(stmt)

        self.indent_level -= 1
        self._add_line("} else {")
        self.indent_level += 1

        for stmt in node.orelse:
            self.visit(stmt)

        self.indent_level -= 1
        self._add_line("};")

    def _visit_expr(self, node: ast.AST) -> str:
        """Visit an expression and return its string representation."""
        if isinstance(node, ast.Compare):
            left = self._visit_expr(node.left)
            op = self._cmp_op_to_sqf(node.ops[0])
            right = self._visit_expr(node.comparators[0])
            return f"{left} {op} {right}"
        elif isinstance(node, ast.Name):
            return node.id
        elif isinstance(node, ast.Num):
            return str(node.n)
        elif isinstance(node, ast.Str):
            return f'"{node.s}"'
        elif isinstance(node, ast.Attribute):
            obj = node.value.id if isinstance(node.value, ast.Name) else "this"
            return f"{obj}.{node.attr}"
        else:
            return "unknown"

    def _cmp_op_to_sqf(self, op: ast.cmpop) -> str:
        """Convert Python comparison operators to SQF."""
        if isinstance(op, ast.Gt):
            return ">"
        elif isinstance(op, ast.Lt):
            return "<"
        elif isinstance(op, ast.GtE):
            return ">="
        elif isinstance(op, ast.LtE):
            return "<="
        elif isinstance(op, ast.Eq):
            return "=="
        elif isinstance(op, ast.NotEq):
            return "!="
        else:
            return "=="  # Default


def transpile_python_to_sqf(source_code: str) -> str:
    """Main entry point for transpiling Python to SQF."""
    transpiler = SQFTranspiler()
    return transpiler.transpile(source_code)