/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("BasicMission")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("mission_name","Operation Python");
    MEMBER("objectives",[]);
    MEMBER("completed_objectives",[]);
    MEMBER("difficulty","normal");
    MEMBER("max_time",3600);
    MEMBER("start_time",0);
};

PUBLIC FUNCTION("any","add_objective") {
    objective = [["id", objective_id], ["description", description], ["required", required], ["completed", unknown], ["progress", 0], ["max_progress", 100]];
this.objectives pushBack objective;
    ;
};

PUBLIC FUNCTION("any","complete_objective") {
    { // for loop
        if (unknown == objective_id) then {
this.completed_objectives pushBack objective_id;
            ;
diag_log unknown;
            ;
        };
    } forEach MEMBER("objectives",nil);
};

PUBLIC FUNCTION("any","get_mission_status") {
    completed_count = (count unknown);
    total_objectives = (count MEMBER("objectives",nil));
    required_completed = (count unknown);
    [["name", MEMBER("mission_name",nil)], ["objectives_completed", completed_count], ["total_objectives", total_objectives], ["required_completed", required_completed], ["success", required_completed == (count unknown)]]
};

PUBLIC FUNCTION("any","check_win_condition") {
    status = MEMBER("get_mission_status",nil);
    unknown
};

PUBLIC FUNCTION("any","initialize_mission") {
diag_log unknown;
    ;
MEMBER("add_objective",["recon", "Conduct reconnaissance of the AO", arg])
    ;
MEMBER("add_objective",["secure", "Secure the objective area", arg])
    ;
MEMBER("add_objective",["extract", "Extract all friendly units", arg])
    ;
MEMBER("add_objective",["bonus", "Destroy enemy communications", arg])
    ;
diag_log unknown;
    ;
};

PUBLIC FUNCTION("any","update_mission") {
    if (unknown) then {
MEMBER("complete_objective",["recon"])
        ;
    };
    if (unknown) then {
MEMBER("complete_objective",["secure"])
        ;
    };
    if (unknown) then {
MEMBER("complete_objective",["extract"])
        ;
    };
};

PUBLIC FUNCTION("any","end_mission") {
    status = MEMBER("get_mission_status",nil);
    if (unknown) then {
diag_log unknown;
        ;
diag_log unknown;
        ;
    } else {
diag_log unknown;
        ;
diag_log unknown;
        ;
    };
};

ENDCLASS;

mission = ["new"] call BasicMission;
MEMBER("initialize_mission",nil)
;
for "_i" from 0 to (0 - 1) do {
MEMBER("update_mission",[time])
    ;
};
MEMBER("end_mission",nil)
;