/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("AISpawnSystem")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("spawned_units",[]);
    MEMBER("unit_types",[["rifleman", ["B_Soldier_F", "O_Soldier_F", "I_Soldier_F"]], ["sniper", ["B_Sniper_F", "O_Sniper_F", "I_Sniper_F"]], ["mg", ["B_Soldier_AR_F", "O_Soldier_AR_F", "I_Soldier_AR_F"]], ["medic", ["B_Medic_F", "O_Medic_F", "I_Medic_F"]]]);
    MEMBER("groups",[]);
};

PUBLIC FUNCTION("any","spawn_unit") {
    if (unit_type == MEMBER("unit_types",nil)) then {
        unit_type = "rifleman";
    };
    class_name = unknown select (floor random count unknown);
    unit = [["id", unknown], ["class", class_name], ["position", position], ["side", side], ["skill", skill], ["group", unknown], ["alive", unknown]];
this.spawned_units pushBack unit;
    ;
    unit
};

PUBLIC FUNCTION("any","spawn_group") {
    group_id = unknown;
    group = [["id", group_id], ["units", []], ["formation", formation], ["side", side], ["leader", unknown]];
    leader = MEMBER("spawn_unit",[leader_position, side, "rifleman", 0.7]);
unknown pushBack leader;
    ;
    for "_i" from 0 to ((size - 1) - 1) do {
        offset = MEMBER("_calculate_formation_offset",[i, formation]);
        unit_pos = [(unknown + unknown), (unknown + unknown), unknown];
        unit = MEMBER("spawn_unit",[unit_pos, side, "rifleman", 0.5]);
unknown pushBack unit;
        ;
    };
this.groups pushBack group;
    ;
    group
};

PUBLIC FUNCTION("any","_calculate_formation_offset") {
    offsets = [["WEDGE", [unknown, unknown, unknown, unknown]], ["LINE", [unknown, unknown, unknown, unknown]], ["COLUMN", [unknown, unknown, unknown, unknown]]];
    if (unknown) then {
        unknown
    };
    unknown
};

PUBLIC FUNCTION("any","move_group") {
    { // for loop
        if (unknown == group_id) then {
            { // for loop
                if (unknown) then {
                };
            } forEach unknown;
        };
    } forEach MEMBER("groups",nil);
};

PUBLIC FUNCTION("any","set_group_behavior") {
    behaviors = ["CARELESS", "SAFE", "AWARE", "COMBAT"];
    combat_modes = ["BLUE", "GREEN", "WHITE", "YELLOW", "RED"];
    if (behavior == behaviors) then {
        behavior = "AWARE";
    };
    if (combat_mode == combat_modes) then {
        combat_mode = "RED";
    };
    { // for loop
        if (unknown == group_id) then {
            { // for loop
            } forEach unknown;
        };
    } forEach MEMBER("groups",nil);
};

PUBLIC FUNCTION("any","get_spawn_statistics") {
    total_units = (count MEMBER("spawned_units",nil));
    alive_units = (count unknown);
    total_groups = (count MEMBER("groups",nil));
    [["total_units", total_units], ["alive_units", alive_units], ["dead_units", (total_units - alive_units)], ["total_groups", total_groups]]
};

PUBLIC FUNCTION("any","cleanup_dead_units") {
    MEMBER("spawned_units",unknown);
    { // for loop
    } forEach MEMBER("groups",nil);
};

ENDCLASS;

ai_system = ["new"] call AISpawnSystem;
group1 = MEMBER("spawn_group",[arg, 4, "WEDGE", "EAST"]);
group2 = MEMBER("spawn_group",[arg, 3, "LINE", "WEST"]);
MEMBER("set_group_behavior",[arg, "COMBAT", "RED"])
;
MEMBER("set_group_behavior",[arg, "AWARE", "YELLOW"])
;
MEMBER("move_group",[arg, arg])
;
MEMBER("move_group",[arg, arg])
;
diag_log unknown;
;
stats = MEMBER("get_spawn_statistics",nil);
diag_log unknown;
;