/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("VehicleSystem")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("vehicles",[]);
    MEMBER("vehicle_types",[["car", ["C_Offroad_01_F", "B_MRAP_01_F", "O_MRAP_02_F"]], ["truck", ["C_Van_01_transport_F", "B_Truck_01_transport_F", "O_Truck_02_transport_F"]], ["tank", ["B_MBT_01_cannon_F", "O_MBT_02_cannon_F"]], ["helicopter", ["B_Heli_Light_01_F", "O_Heli_Light_02_F"]], ["plane", ["B_Plane_CAS_01_F", "O_Plane_CAS_02_F"]]]);
    MEMBER("fuel_stations",[]);
    MEMBER("repair_stations",[]);
};

PUBLIC FUNCTION("any","spawn_vehicle") {
    if (vehicle_type == MEMBER("vehicle_types",nil)) then {
        vehicle_type = "car";
    };
    class_name = unknown select (floor random count unknown);
    vehicle = [["id", unknown], ["class", class_name], ["position", position], ["type", vehicle_type], ["side", side], ["fuel", 1.0], ["damage", 0.0], ["crew", []], ["cargo", []], ["locked", unknown]];
this.vehicles pushBack vehicle;
    ;
    vehicle
};

PUBLIC FUNCTION("any","assign_crew") {
    { // for loop
        if (unknown == vehicle_id) then {
        };
    } forEach MEMBER("vehicles",nil);
};

PUBLIC FUNCTION("any","load_cargo") {
    { // for loop
        if (unknown == vehicle_id) then {
MEMBER("extend",[items])
            ;
        };
    } forEach MEMBER("vehicles",nil);
};

PUBLIC FUNCTION("any","set_vehicle_lock") {
    { // for loop
        if (unknown == vehicle_id) then {
        };
    } forEach MEMBER("vehicles",nil);
};

PUBLIC FUNCTION("any","refuel_vehicle") {
    { // for loop
        if (unknown == vehicle_id) then {
        };
    } forEach MEMBER("vehicles",nil);
};

PUBLIC FUNCTION("any","repair_vehicle") {
    { // for loop
        if (unknown == vehicle_id) then {
        };
    } forEach MEMBER("vehicles",nil);
};

PUBLIC FUNCTION("any","add_fuel_station") {
    station = [["position", position], ["radius", radius], ["type", "fuel"]];
this.fuel_stations pushBack station;
    ;
};

PUBLIC FUNCTION("any","add_repair_station") {
    station = [["position", position], ["radius", radius], ["type", "repair"]];
this.repair_stations pushBack station;
    ;
};

PUBLIC FUNCTION("any","find_nearest_service") {
    stations = unknown;
    if (unknown) then {
        unknown
    };
    nearest = min(stations);
    nearest
};

PUBLIC FUNCTION("any","get_vehicle_status") {
    { // for loop
        if (unknown == vehicle_id) then {
            [["id", unknown], ["class", unknown], ["fuel", unknown], ["damage", unknown], ["crew_count", (count unknown)], ["cargo_count", (count unknown)], ["locked", unknown]]
        };
    } forEach MEMBER("vehicles",nil);
    unknown
};

PUBLIC FUNCTION("any","get_fleet_statistics") {
    total_vehicles = (count MEMBER("vehicles",nil));
    operational = (count unknown);
    damaged = (count unknown);
    out_of_fuel = (count unknown);
    [["total_vehicles", total_vehicles], ["operational", operational], ["damaged", damaged], ["out_of_fuel", out_of_fuel], ["service_stations", ((count MEMBER("fuel_stations",nil)) + (count MEMBER("repair_stations",nil)))]]
};

ENDCLASS;

vehicle_system = ["new"] call VehicleSystem;
MEMBER("add_fuel_station",[arg])
;
MEMBER("add_repair_station",[arg])
;
car = MEMBER("spawn_vehicle",[arg, "car", "WEST"]);
truck = MEMBER("spawn_vehicle",[arg, "truck", "EAST"]);
tank = MEMBER("spawn_vehicle",[arg, "tank", "WEST"]);
MEMBER("load_cargo",[arg, arg])
;
MEMBER("refuel_vehicle",[arg, 0.8])
;
MEMBER("repair_vehicle",[arg, 0.2])
;
diag_log unknown;
;
stats = MEMBER("get_fleet_statistics",nil);
diag_log unknown;
;
nearest_fuel = MEMBER("find_nearest_service",[arg, "fuel"]);
if (nearest_fuel) then {
diag_log unknown;
    ;
};