/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

CLASS("MissionStateMachine")
PUBLIC FUNCTION("array","constructor") {
    MEMBER("current_state","initialization");
    MEMBER("states",[["initialization", [["on_enter", MEMBER("_enter_initialization",nil)], ["transitions", [["start", "briefing"]]]]], ["briefing", [["on_enter", MEMBER("_enter_briefing",nil)], ["transitions", [["accept", "insertion"], ["decline", "aborted"]]]]], ["insertion", [["on_enter", MEMBER("_enter_insertion",nil)], ["transitions", [["landed", "recon"], ["abort", "extraction"]]]]], ["recon", [["on_enter", MEMBER("_enter_recon",nil)], ["transitions", [["target_found", "assault"], ["timeout", "extraction"]]]]], ["assault", [["on_enter", MEMBER("_enter_assault",nil)], ["transitions", [["objective_complete", "extraction"], ["objective_failed", "failed"]]]]], ["extraction", [["on_enter", MEMBER("_enter_extraction",nil)], ["transitions", [["extracted", "debriefing"], ["killed", "failed"]]]]], ["debriefing", [["on_enter", MEMBER("_enter_debriefing",nil)], ["transitions", [["complete", "completed"]]]]], ["completed", [["on_enter", MEMBER("_enter_completed",nil)], ["transitions", []]]], ["failed", [["on_enter", MEMBER("_enter_failed",nil)], ["transitions", []]]], ["aborted", [["on_enter", MEMBER("_enter_aborted",nil)], ["transitions", []]]]]);
    MEMBER("state_data",[]);
    MEMBER("mission_timer",0);
};

PUBLIC FUNCTION("any","start_mission") {
MEMBER("_change_state",["start"])
    ;
};

PUBLIC FUNCTION("any","trigger_event") {
    if (MEMBER("current_state",nil) == MEMBER("states",nil)) then {
        transitions = unknown;
        if (event == transitions) then {
MEMBER("_change_state",[event])
            ;
            unknown
        };
    };
    unknown
};

PUBLIC FUNCTION("any","update") {
    if (MEMBER("current_state",nil) == "recon") then {
        if (MEMBER("mission_timer",nil) > MEMBER("get",["recon_timeout", 300])) then {
MEMBER("trigger_event",["timeout"])
            ;
        };
    } else {
        if (MEMBER("current_state",nil) == "assault") then {
            if (MEMBER("_check_objective_progress",nil) >= 100) then {
MEMBER("trigger_event",["objective_complete"])
                ;
            };
        };
    };
};

PUBLIC FUNCTION("any","get_current_state_info") {
    [["state", MEMBER("current_state",nil)], ["description", MEMBER("_get_state_description",nil)], ["timer", MEMBER("mission_timer",nil)], ["data", MEMBER("state_data",nil)]]
};

PUBLIC FUNCTION("any","_change_state") {
    old_state = MEMBER("current_state",nil);
    if (event == "start") then {
        new_state = "initialization";
    } else {
        if (old_state == MEMBER("states",nil)) then {
            transitions = unknown;
            new_state = MEMBER("get",[event, old_state]);
        } else {
            nil
        };
    };
    if (new_state != old_state) then {
        MEMBER("current_state",new_state);
diag_log unknown;
        ;
        if ("on_enter" == unknown) then {
            ;
        };
    };
};

PUBLIC FUNCTION("any","_get_state_description") {
    descriptions = [["initialization", "Preparing mission systems..."], ["briefing", "Receiving mission briefing"], ["insertion", "Inserting into AO"], ["recon", "Conducting reconnaissance"], ["assault", "Executing assault on objective"], ["extraction", "Extracting from AO"], ["debriefing", "Mission debriefing"], ["completed", "Mission completed successfully"], ["failed", "Mission failed"], ["aborted", "Mission aborted"]];
    MEMBER("get",[arg, "Unknown state"])
};

PUBLIC FUNCTION("any","_check_objective_progress") {
    min(100, (MEMBER("mission_timer",nil) / 10))
};

PUBLIC FUNCTION("any","_enter_initialization") {
diag_log "Mission systems initializing...";
    ;
    MEMBER("state_data",[["initialized", unknown]]);
};

PUBLIC FUNCTION("any","_enter_briefing") {
diag_log "Squad leader: 'Listen up! Here's the mission...'";
    ;
    MEMBER("state_data",[["briefing_given", unknown]]);
};

PUBLIC FUNCTION("any","_enter_insertion") {
diag_log "Insertion helicopter inbound...";
    ;
    MEMBER("state_data",[["insertion_started", unknown]]);
};

PUBLIC FUNCTION("any","_enter_recon") {
diag_log "Moving to recon positions...";
    ;
    MEMBER("state_data",[["recon_timeout", (MEMBER("mission_timer",nil) + 300)]]);
};

PUBLIC FUNCTION("any","_enter_assault") {
diag_log "Assault team moving in!";
    ;
    MEMBER("state_data",[["assault_started", unknown]]);
};

PUBLIC FUNCTION("any","_enter_extraction") {
diag_log "Extraction team en route...";
    ;
    MEMBER("state_data",[["extraction_called", unknown]]);
};

PUBLIC FUNCTION("any","_enter_debriefing") {
diag_log "Welcome back, soldier. Mission debriefing:";
    ;
    success = MEMBER("current_state",nil) == "debriefing";
diag_log unknown;
    ;
};

PUBLIC FUNCTION("any","_enter_completed") {
diag_log "🎉 MISSION ACCOMPLISHED! 🎉";
    ;
    MEMBER("state_data",[["mission_success", unknown]]);
};

PUBLIC FUNCTION("any","_enter_failed") {
diag_log "💀 MISSION FAILED 💀";
    ;
    MEMBER("state_data",[["mission_success", unknown]]);
};

PUBLIC FUNCTION("any","_enter_aborted") {
diag_log "🚫 MISSION ABORTED 🚫";
    ;
    MEMBER("state_data",[["mission_aborted", unknown]]);
};

ENDCLASS;

mission = ["new"] call MissionStateMachine;
MEMBER("start_mission",nil)
;
diag_log unknown;
;
MEMBER("trigger_event",["accept"])
;
diag_log unknown;
;
MEMBER("trigger_event",["landed"])
;
diag_log unknown;
;
MEMBER("trigger_event",["target_found"])
;
diag_log unknown;
;
for "_i" from 0 to (50 - 1) do {
MEMBER("update",[1])
    ;
};
diag_log unknown;
;
diag_log unknown;
;