/*
 * Generated by Parma - Python to SQF Transpiler
 */
#include "macros/oop.h"

// Imported random as random
// Imported math as math
PUBLIC FUNCTION("any","create_units") {
    units = [];
    for "_i" from 0 to (5 - 1) do {
        x = 100 + (random (900 - 100));
        y = 100 + (random (900 - 100));
        unit_name = unknown;
diag_log unknown;
        ;
units pushBack [["name", unit_name], ["position", [x, y, 0]], ["type", "B_soldier_F"]];
        ;
    };
    units
};

PUBLIC FUNCTION("any","move_units_randomly") {
    { // for loop
        new_x = (current_x + unknown + (random (50 - unknown)));
        new_y = (current_y + unknown + (random (50 - unknown)));
        new_x = max(0, min(1000, new_x));
        new_y = max(0, min(1000, new_y));
diag_log unknown;
        ;
    } forEach units;
};

PUBLIC FUNCTION("any","calculate_distances") {
    if ((count units) < 2) then {
        nil
    };
    { // for loop
        { // for loop
            if (i != j) then {
                dx = (unknown - unknown);
                dy = (unknown - unknown);
                distance = sqrt ((dx * dx) + (dy * dy));
                if (distance < 100) then {
diag_log unknown;
                    ;
                };
            };
        } forEach enumerate(units);
    } forEach enumerate(units);
};

PUBLIC FUNCTION("any","mission_loop") {
diag_log "Starting ArmA 3 mission...";
    ;
    units = create_units();
diag_log unknown;
    ;
    for "_loop" from 0 to (3 - 1) do {
diag_log unknown;
        ;
move_units_randomly(units)
        ;
calculate_distances(units)
        ;
    };
diag_log "
Mission complete!";
    ;
};

if (__name__ == "__main__") then {
mission_loop()
    ;
};