#!/usr/bin/env python3
"""
ArmA 3 Mission Generator - Create complete missions with Parma
"""

import os
import json
from pathlib import Path

def create_mission_structure(mission_name: str, output_dir: str = "missions"):
    """Create the basic ArmA 3 mission directory structure."""
    mission_dir = Path(output_dir) / mission_name

    # Create directories
    (mission_dir / "scripts").mkdir(parents=True, exist_ok=True)

    # Create basic mission files
    create_mission_sqm(mission_dir, mission_name)
    create_description_ext(mission_dir)
    create_init_sqf(mission_dir)

    return mission_dir

def create_mission_sqm(mission_dir: Path, mission_name: str):
    """Create the mission.sqm file."""
    mission_sqm = '''version=54;
class EditorData
{
    moveGridStep=1;
    angleGridStep=0.2617994;
    scaleGridStep=1;
    autoGroupingDist=10;
    toggles=1;
    class ItemIDProvider
    {
        nextID=1;
    };
    class MarkerIDProvider
    {
        nextID=1;
    };
    class LayerIndexProvider
    {
        nextID=1;
    };
    class Camera
    {
        pos[]={15000,100,15000};
        dir[]={0,-0.7,-0.7};
        up[]={0,1,0};
        aside[]={1,0,0};
    };
};
class Mission
{
    class Intel
    {
        timeOfChanges=1800.0002;
        startWeather=0.30000001;
        startWind=0.1;
        startWaves=0.1;
        forecastWeather=0.30000001;
        forecastWind=0.1;
        forecastWaves=0.1;
        forecastLightnings=0.1;
        year=2035;
        month=7;
        day=6;
        hour=12;
        minute=0;
        startFogDecay=0.013;
        forecastFogDecay=0.013;
    };
    class Entities
    {
    };
    class Connections
    {
    };
};
'''

    with open(mission_dir / "mission.sqm", 'w') as f:
        f.write(mission_sqm)

def create_description_ext(mission_dir: Path):
    """Create the description.ext file."""
    description_ext = '''author = "Parma Mission Generator";
onLoadName = "Parma Generated Mission";
onLoadMission = "A mission created with Parma - Python to SQF transpiler";
loadScreen = "";

class CfgDebriefing
{
    class End1
    {
        title = "Mission Completed";
        subtitle = "You have successfully completed the mission.";
        description = "Well done!";
    };
};

class CfgSounds
{
    sounds[] = {};
};
'''

    with open(mission_dir / "description.ext", 'w') as f:
        f.write(description_ext)

def create_init_sqf(mission_dir: Path):
    """Create the init.sqf file that loads our Parma scripts."""
    init_sqf = '''// Parma Mission Init
// This file is automatically generated

// Load Parma transpiled scripts
execVM "scripts\\main.sqf";

// Mission initialization complete
systemChat "Parma mission loaded successfully!";
'''

    with open(mission_dir / "init.sqf", 'w') as f:
        f.write(init_sqf)

def generate_combat_patrol_mission():
    """Generate a complete combat patrol mission."""

    mission_code = '''
import math
import random
from game_framework import Vector3, Unit, World, GameManager

# Mission: Combat Patrol
# Player must eliminate enemy patrols and secure the area

def setup_patrol_routes():
    """Create patrol routes around the AO."""
    routes = [
        [Vector3(14500, 14500, 0), Vector3(15000, 14500, 0), Vector3(15000, 15000, 0)],
        [Vector3(15500, 14500, 0), Vector3(15500, 15000, 0), Vector3(15000, 15000, 0)],
        [Vector3(14500, 15500, 0), Vector3(15000, 15500, 0), Vector3(15500, 15500, 0)],
    ]
    return routes

def spawn_enemy_patrol(route, patrol_id):
    """Spawn an enemy patrol following a route."""
    units = []

    # Spawn 4 soldiers per patrol
    formations = [
        Vector3(0, 0, 0),      # Leader
        Vector3(5, 5, 0),      # Right flank
        Vector3(-5, 5, 0),     # Left flank
        Vector3(0, 10, 0),     # Rear guard
    ]

    start_pos = route[0]
    for i, offset in enumerate(formations):
        pos = Vector3(
            start_pos.x + offset.x,
            start_pos.y + offset.y,
            start_pos.z + offset.z
        )

        unit = Unit(pos, "O_soldier_F", "enemy")
        unit.patrol_route = route
        unit.waypoints = route[1:] + [route[0]]  # Loop the route
        units.append(unit)

    return units

def setup_objectives():
    """Set up mission objectives."""
    objectives = [
        {
            "id": "eliminate_patrols",
            "title": "Eliminate Enemy Patrols",
            "description": "Eliminate all enemy patrols in the area",
            "type": "destroy",
            "completed": False
        },
        {
            "id": "secure_area",
            "title": "Secure the Area",
            "description": "Ensure no enemy presence remains",
            "type": "clear",
            "completed": False
        }
    ]
    return objectives

def check_mission_completion(world, objectives):
    """Check if mission objectives are complete."""
    # Check if all enemy patrols are eliminated
    enemy_count = len([u for u in world.units if u.faction == "enemy" and u.health > 0])
    if enemy_count == 0 and not objectives[0]["completed"]:
        objectives[0]["completed"] = True
        print("Objective completed: Enemy patrols eliminated")

    # Check if area is secure (no enemies for 30 seconds)
    if objectives[0]["completed"] and not objectives[1]["completed"]:
        # In a real implementation, you'd track time
        objectives[1]["completed"] = True
        print("Mission completed: Area secured")

    return all(obj["completed"] for obj in objectives)

def spawn_player():
    """Spawn the player unit."""
    player_pos = Vector3(15000, 14200, 0)  # South of the AO
    player = Unit(player_pos, "B_soldier_F", "player")
    player.health = 100
    return player

def mission_init():
    """Initialize the combat patrol mission."""
    print("Initializing Combat Patrol Mission...")

    # Create world
    world = World()

    # Spawn player
    player = spawn_player()
    world.add_object(player)

    # Set up patrol routes
    routes = setup_patrol_routes()

    # Spawn enemy patrols
    for i, route in enumerate(routes):
        patrol_units = spawn_enemy_patrol(route, i)
        for unit in patrol_units:
            world.add_object(unit)

    # Set up objectives
    objectives = setup_objectives()

    print(f"Mission initialized: {len(world.units)} units, {len(routes)} patrols")
    return world, objectives, player

def mission_update(world, objectives, player):
    """Update mission state each frame."""
    # Update AI for enemy units
    for unit in world.units:
        if unit.faction == "enemy" and unit.health > 0:
            update_enemy_ai(unit, world)

    # Check mission completion
    if check_mission_completion(world, objectives):
        print("Mission accomplished!")
        return True  # Mission complete

    return False

def update_enemy_ai(unit, world):
    """Update AI for enemy patrol units."""
    # Simple patrol AI
    if hasattr(unit, 'waypoints') and unit.waypoints:
        # Move towards next waypoint
        next_waypoint = unit.waypoints[0]
        distance = unit.position.distance(next_waypoint)

        if distance < 5:  # Reached waypoint
            unit.waypoints.pop(0)
            if not unit.waypoints:  # Loop the patrol
                # Reset waypoints (this would be the patrol route)
                unit.waypoints = unit.patrol_route[1:] + [unit.patrol_route[0]]
        else:
            # Move towards waypoint
            direction = (next_waypoint - unit.position).normalize()
            unit.position.x += direction.x * unit.speed * 0.016  # Assuming 60 FPS
            unit.position.y += direction.y * unit.speed * 0.016
            unit.position.z += direction.z * unit.speed * 0.016

def main():
    """Main mission entry point."""
    world, objectives, player = mission_init()

    # Mission loop (would be called each frame in ArmA)
    mission_complete = False
    frame_count = 0

    while not mission_complete and frame_count < 3600:  # 60 seconds at 60 FPS
        mission_complete = mission_update(world, objectives, player)
        frame_count += 1

        # Periodic status updates
        if frame_count % 600 == 0:  # Every 10 seconds
            enemy_count = len([u for u in world.units if u.faction == "enemy" and u.health > 0])
            print(f"Status: {enemy_count} enemies remaining, frame {frame_count}")

    if mission_complete:
        print("Combat Patrol Mission: SUCCESS")
    else:
        print("Combat Patrol Mission: FAILED - Time limit exceeded")

if __name__ == "__main__":
    main()
'''

    return mission_code

def generate_mission(mission_type: str = "combat_patrol", mission_name: str = "ParmaCombatPatrol"):
    """Generate a complete ArmA 3 mission."""

    # Create mission directory structure
    mission_dir = create_mission_structure(mission_name)

    # Generate Python mission code
    if mission_type == "combat_patrol":
        python_code = generate_combat_patrol_mission()
    else:
        python_code = generate_combat_patrol_mission()  # Default

    # Write Python code
    with open(mission_dir / "scripts" / "main.py", 'w') as f:
        f.write(python_code)

    # Transpile to SQF using Parma
    import subprocess
    import sys
    from pathlib import Path

    # Get the project root (parent of tools directory)
    project_root = Path(__file__).parent.parent
    sys.path.insert(0, str(project_root))

    # Ensure the Python file exists
    python_file = mission_dir / 'scripts' / 'main.py'
    if not python_file.exists():
        print(f"❌ Python file not found: {python_file}")
        return None

    result = subprocess.run([
        sys.executable, "-c",
        f"from src.parma.cli import main; import sys; sys.argv = ['parma', 'compile', '{python_file.resolve()}']; main()"
    ], capture_output=True, text=True, cwd=project_root)

    if result.returncode == 0:
        print(f"✅ Mission generated successfully: {mission_dir}")
        print("📁 Mission structure created")
        print("🐍 Python code written")
        print("⚡ SQF transpilation completed")

        # Create a README for the mission
        create_mission_readme(mission_dir, mission_type)

        return mission_dir
    else:
        print(f"❌ Failed to generate mission: {result.stderr}")
        return None

def create_mission_readme(mission_dir: Path, mission_type: str):
    """Create a README for the generated mission."""
    readme = f'''# Parma Generated Mission: {mission_dir.name}

## Mission Type: {mission_type.replace('_', ' ').title()}

This mission was automatically generated using Parma - a Python-to-SQF transpiler for ArmA 3.

## Files Structure

```
{mission_dir.name}/
├── mission.sqm          # ArmA mission definition
├── description.ext      # Mission configuration
├── init.sqf            # Mission initialization
└── scripts/
    ├── main.py         # Original Python code
    └── main.sqf        # Transpiled SQF code
```

## How to Use

1. Copy this entire folder to your ArmA 3 missions directory
2. Launch ArmA 3 with the editor
3. Load this mission in the editor
4. Play or export to multiplayer

## Generated Code

The Python code in `scripts/main.py` was transpiled to SQF in `scripts/main.sqf`.
The SQF code is loaded automatically when the mission starts via `init.sqf`.

## Parma Features Used

- Game framework classes (Vector3, Unit, World)
- Python control structures (if/else, for loops, functions)
- Math operations (distance calculations, vector math)
- Random number generation
- Object-oriented programming

## Customization

To modify this mission:
1. Edit `scripts/main.py`
2. Run Parma to transpile: `parma compile scripts/main.py`
3. Reload the mission in ArmA 3

## Requirements

- ArmA 3
- Parma transpiler (for modifications)

---
Generated with Parma v2.0.0
'''

    with open(mission_dir / "README.md", 'w') as f:
        f.write(readme)

if __name__ == "__main__":
    # Generate a combat patrol mission
    mission_dir = generate_mission("combat_patrol", "ParmaCombatPatrol.Tanoa")

    if mission_dir:
        print(f"\n🎮 Mission ready at: {mission_dir}")
        print("🚀 Copy to your ArmA 3 missions folder and play!")